### ISSUE TITLE
heredoc 작동 안함

### ISSUE THREAD

**Issue by jhon3242** [jhon3242/minishell#17]
`wc -l << heredoc`
명령어 입력시 heredoc 이 실행되어 새롭게 명령어를 입력받아야 하는데 작동되지 않음

**Comment by jhon3242** [comment]
`wc -l << heredoc` 명령어 입력시에 `parse` 함수에서 cmd 구조체에 argv[2] 의 값에 `<<` 로 지정한 `-74-74\0` 가 들어가여 하는데 `-74\0` 만 들어 있어서 heredoc 체크시 안잡히는 것 같습니다. `-74-74\0` 가 들어가도록 수정 부탁드립니다!

@tehyoyee

**Comment by tehyoyee** [comment]
> `wc -l << heredoc` 명령어 입력시에 `parse` 함수에서 cmd 구조체에 argv[2] 의 값에 `<<` 로 지정한 `-74-74\0` 가 들어가여 하는데 `-74\0` 만 들어 있어서 heredoc 체크시 안잡히는 것 같습니다. `-74-74\0` 가 들어가도록 수정 부탁드립니다!
> 
> @tehyoyee

알겠습니다 !

**Comment by tehyoyee** [comment]
고쳤습니다 노트북이 컴파일이 잘안돼서 헤맸네요.

**Comment by jhon3242** [comment]
> 고쳤습니다 노트북이 컴파일이 잘안돼서 헤맸네요.

감사합니다!! 이제 정상적으로 작동하네요!
