### ISSUE TITLE
echo 따음표 사용시 버그

### ISSUE THREAD

**Issue by jhon3242** [jhon3242/minishell#24]
`echo '$HOME'` 입력시에는 그냥 `$HOME` 이 출력되어야 하는데 `$HOME` 에 해당하는 값이 출력되버린다.

**Comment by jhon3242** [comment]
@tehyoyee 
제가 고쳐보려고 했는데 제가 짠 함수가 아니여서 그런지 찾기가 힘드네요 ㅠ 디버깅 해보니까 replace 함수 안에 있는 get_replaced_cmd 에서 값이 바뀌는 것 같습니다!

**Comment by tehyoyee** [comment]
해결.!
